[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://fitness-tracker-pklg.onrender.com/api"
  REACT_APP_BACKEND_URL = "https://fitness-tracker-pklg.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
